### ISSUE TITLE
file .java missing in project created

### ISSUE THREAD

**Issue by nicolapagni** [spinscale/cookiecutter-elasticsearch-ingest-processor#10] opened 2019-05-10 15:50 UTC
Hi,

I've cloned this repo, then i run the following:

_cookiecutter cookiecutter-elasticsearch-ingest-processor_

It creates the scaffolding of all ingestProcessos, except all files *.java

I tried to write manually those files, but when i run gradlew clean check I've the following error:

C:\Users\nicol\Desktop\test\ingest-tintnlp
λ gradlew clean check
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details

> Configure project :
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.2.1
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [Java HotSpot(TM) 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : C:\Program Files\Java\jdk-12.0.1
  Random Testing Seed   : B824F80B0B131EED
=======================================

> Task :jar
Building without git revision id.

> Task :testingConventions FAILED
Expected at least one test class included in task :integTestRunner, but found none.
Expected at least one test class included in task :test, but found none.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testingConventions'.
> Testing conventions are not honored

Thanks in advance,
  Nicola

**Comment by spinscale** [comment] 2019-05-16 14:26
can you explain to me, what you did differently than what I did?

Here is a screenshot of cloning the repo, running cookiecutter and listing the files recursively

![image](https://user-images.githubusercontent.com/667544/57861651-f89f5e00-77c4-11e9-8060-67b8f59f8c6a.png)

as you can see all the java files are there.

What operating system are you running on?

**Comment by spinscale** [comment] 2019-05-21 15:28
oh, I just noticed that my requested information is actually there. Running on windows seems to have problems with overly long file names. See #4 and #9 

I'd appreciate any help on this, but I do not have any windows system to test.

**Comment by spinscale** [comment] 2019-08-13 11:56
closing as duplicate of #4

**Closed as completed by spinscale** 2019-08-13 11:56 UTC

**Comment by hkulekci** [comment] 2020-11-15 01:32
I got same error on MacOSx after getting latest updates related with 7.10.0. It ran with version 7.9.1

**Comment by hkulekci** [comment] 2020-11-15 01:32
ping @spinscale

**Comment by spinscale** [comment] 2020-11-15 21:42
please open a new issue and share the fulloutput of your run.

thanks

**Comment by hkulekci** [comment] 2020-11-30 09:15
No need to open new issue. I want to put here to be able to find again if I got stuck again 😄  

 - You need to commit at least one commit after `git init`
 - You need to check java, jdk and `gradlew` version. I update the `gradlew` file to be able to use with `java 15.0.1`

Thank you @spinscale
